// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  hero: dynamic(() => import('./Hero')),
  text_body: dynamic(() => import('./TextBody')),
};
